CONFIG_EC11=y

# nice!nano v2 uses P0.09/P0.10 as NFC pins by default; matrix cols use them as GPIO.
CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

CONFIG_ZMK_SLEEP=y

CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_STUDIO=y
